version: "3.9"
services:
  qrcode:
    container_name: QR-Code-Generator
    image: bizzycolah/qrcode-generator:latest
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 8895:80
version: "3.3"
services:
  twportainer:
    image: portainer/portainer-ce:latest
    container_name: twportainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer:/data
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 7890:8080
    volumes:
      - /volume1/docker/stirling/data:/usr/share/tessdata:rw # Required for extra OCR languages
      - /volume1/docker/stirling/config:/configs:rw
      - /volume1/docker/stirling/logs:/logs:rw
    environment:
     PUID: 1026
     PGID: 100
     DOCKER_ENABLE_SECURITY: true # or false
     SECURITY_ENABLELOGIN: true #or false
     SECURITY_INITIALLOGIN_USERNAME: aizen
     SECURITY_INITIALLOGIN_PASSWORD: Qweqwe123  
     INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false #or true
     SECURITY_CSRFDISABLED: true #or false
     SYSTEM_DEFAULTLOCALE: en_US # or fr_FR or de_DE
     UI_APPNAME: mariusPDF
     UI_HOMEDESCRIPTION: aizen PDF Description
     UI_APPNAMENAVBAR: aizen PDF
     SYSTEM_MAXFILESIZE: 5000 # Set the maximum file size in MB
     METRICS_ENABLED: true
     SYSTEM_GOOGLEVISIBILITY: false # or true
    restart: on-failure:5
