version: "3.9"
services:
 homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /volume1/docker/homeassistant:/config
    ports:
      - "8123:8123"
    restart: always
 hass-configurator:
    container_name: configurator
    image: causticlab/hass-configurator-docker:latest
    volumes:
      - /volume1/docker/fileeditor:/config
      - /volume1/docker/homeassistant:/hass-config
    restart: always
    ports:
      - "3218:3218/tcp"