version: "3.9"
services:
 twportainer:
    image: portainer/portainer-ce:latest
    container_name: twportainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer:/data
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
 drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 5022:8080
 adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /volume1/docker/adguard/config:/opt/adguardhome/conf
      - /volume1/docker/adguard/data:/opt/adguardhome/work
    network_mode: host
    restart: unless-stopped
 uptime-kuma:
    image: elestio/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
    - /volume1/docker/kuma/data:/app/data
    ports:
    - 3002:3001
    restart: always
 dashy:
    container_name: Dashy
    image: lissy93/dashy
    volumes:
       - /volume1/docker/dashy/conf.yml:/app/user-data/conf.yml
    ports:
      - 4040:8080
    environment:
      UID: 1026
      GID: 100
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
 webcheck:
    container_name: Web-Check
    image: lissy93/web-check
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 6160:3000
 tubesync:
    container_name: Tubesync
    image: ghcr.io/meeb/tubesync:latest
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 4848:4848
    volumes:
      - /volume1/docker/tubesync/config:/config:rw
      - /volume1/docker/tubesync/downloads:/downloads:rw
    environment:
     TZ: Europe/Bucharest
     HTTP_USER: aizen
     HTTP_PASS: <fhhfrelf_21-02
     PUID: 1026
     PGID: 100
 db:
    image: postgres:16
    container_name: Linkwarden-DB
    hostname: linkwarden-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/linkwarden/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: linkwardenpass
    restart: on-failure:5
 linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: Linkwarden
    hostname: linkwarden
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 7461:3000
    volumes:
      - /volume1/docker/linkwarden/data:/data/data:rw
    environment:
      DATABASE_URL: postgres://linkwardenuser:linkwardenpass@linkwarden-db:5432/linkwarden
      NEXTAUTH_SECRET: v6M37byB5LwYHCPZyCJzDGNUSsHY4grj
      NEXTAUTH_URL: http://localhost:3000/api/v1/auth
      NEXT_PUBLIC_DISABLE_REGISTRATION: false #or true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 7890:8080
    volumes:
      - /volume1/docker/stirling/data:/usr/share/tessdata:rw # Required for extra OCR languages
      - /volume1/docker/stirling/config:/configs:rw
      - /volume1/docker/stirling/logs:/logs:rw
    environment:
     PUID: 1026
     PGID: 100
     DOCKER_ENABLE_SECURITY: true # or false
     SECURITY_ENABLELOGIN: true #or false
     SECURITY_INITIALLOGIN_USERNAME: aizen
     SECURITY_INITIALLOGIN_PASSWORD: Qweqwe123   
     INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false #or true
     SECURITY_CSRFDISABLED: true #or false
     SYSTEM_DEFAULTLOCALE: en_US # or fr_FR or de_DE
     UI_APPNAME: aizenPDF
     UI_HOMEDESCRIPTION: Aizen PDF Description
     UI_APPNAMENAVBAR: Aizen PDF
     SYSTEM_MAXFILESIZE: 5000 # Set the maximum file size in MB
     METRICS_ENABLED: true
     SYSTEM_GOOGLEVISIBILITY: false # or true
    restart: on-failure:5
  codeserver:
    container_name: Code-Server
    image: ghcr.io/linuxserver/code-server
    healthcheck:
     test: curl -f http://localhost:8443/ || exit 1
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 8377:8443
    volumes:
      - /volume1/docker/codeserver:/config:rw
    environment:
      TZ: Europe/Bucharest
      PUID: 1026
      PGID: 100
      PROXY_DOMAIN: cr.aizen.myds.me
      PASSWORD: <fhhfrelf_21-02
      SUDO_PASSWORD: <fhhfrelf_21-02